version: "3.8"

#docker-compose up --build

#PostgreSQL chạy ở localhost:5432.
#MongoDB chạy ở localhost:27017.
#RabbitMQ chạy ở:
#Broker: amqp://localhost:5672
#UI quản lý: http://localhost:15672 (user admin / pass secret).
#User Service chạy ở: http://localhost:8081.

services:
  # Database
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8086:80"
    depends_on:
      - postgres

  mongodb:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # RabbitMQ cho async communication
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # RabbitMQ broker port
      - "15672:15672" # RabbitMQ management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  # User Service (service đầu tiên của bạn)
  user-service:
    build:
      context: ../user-service # thư mục chứa Dockerfile và code user-service
      dockerfile: Dockerfile # Dockerfile bạn vừa sửa để dùng JDK 21
    container_name: user-service
    ports:
      - "8081:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: admin
      DB_PASSWORD: secret
    depends_on:
      - postgres
      - rabbitmq

  product-service:
    build: ../product-service
    container_name: product-service
    ports:
      - "8082:8080"
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: products_db
    depends_on:
      - mongodb

  api-gateway:
    build: ../api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service

volumes:
  postgres_data:
  mongo_data:
