version: "3.8"

# docker-compose up --build

services:
  # ====================
  # PostgreSQL + pgAdmin
  # ====================
  postgres:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secret}
      POSTGRES_DB: ${POSTGRES_DB:-users_db}
    ports:
      - "5433:5432" # Host:5433 -> Container:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_dev
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8086:80"
    depends_on:
      - postgres

  # ==========
  # MongoDB
  # ==========
  mongodb:
    image: mongo:6
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # =========================
  # RabbitMQ (Message Broker)
  # =========================
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672" # Broker
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: secret

  # ================
  # User Service
  # ================
  user-service:
    build:
      context: ../user-service # Thư mục code user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8080" # Host:8081 -> Container:8080
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: users_db
      DB_USER: admin
      DB_PASSWORD: secret
    depends_on:
      - postgres
      - rabbitmq

  # =================
  # Product Service
  # =================
  product-service:
    build:
      context: ../product-service
      dockerfile: Dockerfile
    container_name: product-service
    ports:
      - "8082:8080" # Host:8082 -> Container:8080
    environment:
      DB_HOST: mongodb
      DB_PORT: 27017
      DB_NAME: products_db
    depends_on:
      - mongodb

  # ================
  # API Gateway
  # ================
  api-gateway:
    build:
      context: ../api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - user-service
      - product-service

volumes:
  postgres_data:
  mongo_data:
